stages:
    - deploy

build_web:
    stage: deploy
    script:
        - echo "Compressing web directory."
        - cd ./system/web
        - tar -zcvf ../../web.tar.gz .
        - cd ../..
    artifacts:
        paths:
            - web.tar.gz
        expire_in: 8 weeks