stages:
    - deploy

build_web:
    stage: deploy
    script:
        - echo "Compressing web directory."
        - tar -zcvf web.tar.gz ./system/web
    artifacts:
        paths:
            - web.tar.gz
        expire_in: 8 weeks